### ISSUE TITLE
Guild, a nil value

### ISSUE THREAD

**Issue by SamBehner** [SinisterRectus/Discordia#144] opened 2018-09-07 19:49 UTC
Whenever I try to use guild, it returns a nil value: ex.

`value = "There are currently have "..tostring(guild.totalMemberCount) " members."`

returns
`attempt to index global 'guild' (a nil value)`

**Comment by SinisterRectus** [comment] 2018-09-07 19:53
As the error message says, `guild` is nil. You need to define it.

**Comment by SamBehner** [comment] 2018-09-10 14:36
How could I define it, im assuming I would have to reach it by something like

`local server = message.guild;`

**Comment by PurgePJ** [comment] 2018-09-10 14:37
In your case it would be:

`local guild = message.guild`

and only if you are doing this with a message object (for example in messageCreate event).

**Comment by SamBehner** [comment] 2018-09-10 14:42
yeah, I got it working with

`message.channel.guild`

**Comment by PurgePJ** [comment] 2018-09-10 14:44
If you are receiving a message object, `guild` should be also accessible from `message.guild`. As docs state:

`The guild in which this message was sent. This will not exist if the message
was not sent in a guild text channel. Equivalent to Message.channel.guild`

**Comment by PurgePJ** [comment] 2018-09-10 14:45
Also if the issue is resolved please close it 💃

**Closed** 2018-09-14 15:08 UTC
Labels: invalid
