### ISSUE TITLE
How to make an image from API generators in embed messages?

### ISSUE THREAD

**Issue by lucaarc** [SinisterRectus/Discordia#245] opened 2020-05-27 14:50 UTC
### **Hi,**
I'm little bit of a noob when it comes to coding and I decided to start with the simple task of making a lua bot. However, I have hit a road block:
I want to make a discord bot generate memes through an api. I already had it set up, and it worked for me until I decided to make it embed. I get an error when I try to make it embed. Here's my code and error: 
```
function Memes(message)
	coroutine.wrap(function()
		local link = "https://meme-api.herokuapp.com/gimme"
		local result, body = coro.request("GET", link)
		body = json.parse(body)
		--message:reply("<@!"..message.member.id.."> "..body["title"].." "..body["url"])
		message:reply{
			embed = {
				title = body["title"];
				image = {
					url = ["url"]
				},
				color = discordia.Color.fromRGB(100,60,255).value;
			};
		}
	end)()
end
```
My error:
```
Uncaught exception:
[string "bundle:deps/require.lua"]:301: C:\luvit\bot.lua:16: unexpected symbol near '['
stack traceback:
        [C]: in function 'assert'
        [string "bundle:deps/require.lua"]:301: in function 'require'
        [string "bundle:/main.lua"]:118: in function 'main'
        [string "bundle:/init.lua"]:49: in function <[string "bundle:/init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:/init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>
```
I am really confused, and tried sharing my problem on the discord but I didn't get much help.
They said to make sure the URL is a valid image, and it is. The code works fine without embed, just like this.
`message:reply("<@!"..message.member.id.."> "..body["title"].." "..body["url"])`
That works fine, it sends me the title (the text of the meme) and the url which then shows a picture. 
Here's an image from the non embed working code:
![image](https://user-images.githubusercontent.com/35407852/83035686-c182a000-a007-11ea-8d1d-2a4ec4cde47d.png)

**Any help with this problem would greatly be appreciated, and know that I am not super experienced so I won't always know exactly what you're saying.**

**Comment by Bilal2453** [comment] 2020-05-29 02:57
Hi Lucaar,

> I decided to start with the simple task of making a lua bot.

Discord bots are actually advanced task to take for just training on the language, as making a bot includes advanced acknowledge of RESTful APIs and their technical side, or at least the basics of the language you are working with.

This problem is mainly caused by the poor acknowledge of Lua as there are many bad programming practices, and syntax errors (your current) in formatting the table and many other problems.

As the github issues are only meant for bugs and suggestions not for questions like this, I can't help you here any further, you should come and join our discord at discord.gg/discord-api and ask in \#lua_discordia channel.

You are welcome there for any questions \:)
I hope if this reply helped you, you close this issue as it is in the wrong place.

Good luck.

**Closed** 2020-05-29 13:59 UTC
